Controllers/CProspectoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Prospecto.Data;
using Prospecto.Models;
using Prospecto.Repositorio;
using static Prospecto.Enums.Enums;

namespace Prospecto.Controllers
{
    [Authorize]
    public class CProspectoController : BaseController
    {
        private readonly CRepository<ProspectoModel> gRepository;
        private readonly CRepository<ColoniaModel> cRepository;
        private readonly CRepository<CalleModel> lRepository;

        IHttpContextAccessor _httpContextAccessor;

        string[] lParam = { };
        string[] lVar = { };
        string[] lParametros = { "@Opc", "@Id","@Nombre","@PrimerApellido","@SegundoApellido","Calle",
                                "@Numero","@Colonia","@Telefono","@RFC" };

        public CProspectoController(ConnectionConfiguration _configuration, IHttpContextAccessor httpContextAccessor)
        {
            gRepository = new CRepository<ProspectoModel>(_configuration);
            cRepository = new CRepository<ColoniaModel>(_configuration);
            lRepository = new CRepository<CalleModel>(_configuration);
            _httpContextAccessor = httpContextAccessor;
        }
        public async Task<IActionResult> Index(string searchString = "@")
        {
            lParam = new string[] { "@Opc", "@Nombre" };
            lVar = new string[] { "2", searchString };
            IEnumerable<ProspectoModel> Lista = await gRepository.BDLista("c_spProspecto", lParam, lVar);

            return View("Index", Lista);
        }


        [HttpGet]
        public async Task<IActionResult> AddEdit(int? id)
        {
            ProspectoModel model = new ProspectoModel();
            ViewBag.Id = null;

            if (id.HasValue) //cuando se va editar uno existente
            {
                lParam = new string[] { "@Opc", "@Id" };
                lVar = new string[] { "3", id.Value.ToString() };
                model = await gRepository.BDBuscarReg("c_spProspecto", lParam, lVar);

                ViewBag.Id = model.ID;
                model.SCol1 = model.ColoniaNom;

                string NomRol = _httpContextAccessor.HttpContext.User.FindFirst("Role").Value.ToString().Trim();

                ViewBag.Status = model.Estatus == "Autorizado" || model.Estatus == "Rechazado" || NomRol=="PROMOTOR" ? "T" : "";
                if (ViewBag.Status == "T")
                {
                    ViewBag.StatusText = model.Estatus == "Autorizado" ? "- A U T O R I Z A D O -" : model.Estatus == "Rechazado"?"- R E C H A Z A D O - : " + model.Comentario.Trim():"";
                }
 
                GetCalle(model, model.Colonia);
            }
            return View("~/Views/CProspecto/AddEdit.cshtml", model);
        }

        [HttpGet]
        public async Task<IActionResult> AddEdit2(int? id)
        {
            ProspectoModel model = new ProspectoModel();
            ViewBag.Id = null;

            if (id.HasValue) //cuando se va editar uno existente
            {
                lParam = new string[] { "@Opc", "@Id" };
                lVar = new string[] { "3", id.Value.ToString() };
                model = await gRepository.BDBuscarReg("c_spProspecto", lParam, lVar);

                ViewBag.Id = model.ID;
                ViewBag.ColoniaNom = model.SCol1.Trim();
                ViewBag.CalleNom = model.CalleNom.Trim();

                string NomRol = _httpContextAccessor.HttpContext.User.FindFirst("Role").Value.ToString().Trim();

                ViewBag.Status = model.Estatus == "Autorizado" || model.Estatus == "Rechazado" || NomRol == "PROMOTOR" ? "T" : "";
                if (ViewBag.Status == "T")
                {
                    ViewBag.StatusText = model.Estatus == "Autorizado" ? "- A U T O R I Z A D O -" : model.Estatus == "Rechazado" ? "- R E C H A Z A D O - : " + model.Comentario.Trim() : "";
                }

                GetCalle(model, model.Colonia);
            }
            return View("~/Views/CProspecto/Autorizar.cshtml", model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Guardar(ProspectoModel cust, List<IFormFile> files)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    lVar = LlenarAray(cust);
                    int idl=await gRepository.BDAddAsync("c_spProspecto", lParametros, lVar);//Guarda Dato nuevo o Modificado
                    if (idl != 0)
                    {
                        await GuardarArchivo(files,idl);
                    }
                    Alert("El Dato Fue Guardado", NotificationType.success);
                    return RedirectToAction("Index");
                }
                return View("~/Views/CProspecto/AddEdit.cshtml", cust);
            }
            catch (Exception ex)
            {
                throw new Exception("An error occurred...",ex);
            }
        }
        private async Task GuardarArchivo(List<IFormFile> files,int idx)
        {
            try
            {
                foreach (IFormFile aformFile in files)
                {
                    var formFile = aformFile;
                    if (formFile.Length > 0)
                    {
                        //Subir archivo a la base de datos
                        //Obtener nombre de archivo
                        var filename = Path.GetFileName(formFile.FileName);
                        //Obtener extensión de archivo  
                        var fileextension = Path.GetExtension(filename);
                        // concatenar nombre de archivo y extensión de archivo   
                        var newfilename = filename;
                            //String.Concat(Convert.ToString(Guid.NewGuid()), fileextension);
                        var documentViewmodel = new DocumentModel()
                        {
                            Id = 0,
                            FileName = newfilename,
                            FileType = fileextension,
                            Created = DateTime.Now,
                            Modified = DateTime.Now,
                            IdProspecto = idx
                        };
                        using (var target = new MemoryStream())
                        {
                            formFile.CopyTo(target);
                            documentViewmodel.FileData = target.ToArray();
                        }

                        await gRepository.BDAddFileAsync(documentViewmodel);
                    }
                }
            }
            catch (Exception ex)
            {
                throw new Exception("An error occurred...", ex);
            }
        }
        public async Task<IActionResult> Autorizado(int id)
        {
            lParam = new string[] { "@Opc","@Id", };
            lVar = new string[] { "4",id.ToString() };
            await gRepository.BDAddAsync("c_spProspecto", lParam, lVar);
            var result = new { param1 = "Ok" };
            return Json(result);
        }

        public IActionResult Rechazar(int id)
        {
            ProspectoModel model = new ProspectoModel();
            model.ID = id;
            return PartialView("~/Views/CProspecto/_ProsRechazo.cshtml", model);
        }

        [HttpPost]
        public ActionResult AutoComplete(string Prefix)
        {
            ProspectoModel R = new ProspectoModel();
            if (!String.IsNullOrEmpty(Prefix))
            {
                return Json(GetAuto(R, Prefix, 2));
            }
            else
            {
                return Json(GetAuto(R, "", 2));
            }
        }
        public async Task<IActionResult> GuardarComR_Accion(string ID, string comentario)
        {
            lParam = new string[] { "@Opc","@Id","@Nombre" };
            lVar = new string[] { "5", ID.Trim(), comentario.ToUpper() };
            await gRepository.BDAddAsync("c_spProspecto", lParam, lVar);
            return Json("SAVE");
        }

        List<ColoniaModel> GetAuto(ProspectoModel model, string ParamFijo, int opc)
        {
            string[] lParametros = { "@Opc", "@Nom" };
            string[] lVariables = { opc.ToString(), ParamFijo.Trim() };
            var util = cRepository.BDListaCombo("c_spColonia", lParametros, lVariables);

            return util.ToList();
        }

        public ActionResult Llenar_Calle(string col, int opc)
        {
            ProspectoModel R = new ProspectoModel();
            return Json(GetCalle(R, col, opc));
        }
        IEnumerable<SelectListItem> GetCalle(ProspectoModel model, string lxcol, int Opc = 1)
        {
            var Combol = new List<SelectListItem>();

            if (lxcol != null)
            {
                string[] lParametros = { "@Opc", "@CodigoCol" };
                string[] lVariables = { "2", lxcol.Trim() };
                var cal = lRepository.BDListaCombo("c_spCalle", lParametros, lVariables);

                var listacal = cal.ToList();

                foreach (var Data in listacal)
                {
                    model.Cal1.Add(new SelectListItem()
                    {
                        Value = Data.CodigoCalle,
                        Text = Data.Nombre
                    });
                }
            }
            return model.Cal1;
        }
        //------------------------------------------
        //--------------------Nueva Calle
        public IActionResult AddCalle()
        {
            CalleModel model = new CalleModel();
            //ViewBag.idCol = id;
            return PartialView("~/Views/CProspecto/_NewCalle.cshtml", model);
        }
        public async Task<ActionResult> NewCalleAjax(string lcol, string lcalle)
        {
            lParam = new string[] { "@Opc", "@Cod", "@Nom", "@CodigoCol" };
            lVar = new string[] { "3", "0", lcalle, lcol.PadLeft(5,'0') };

Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using static Prospecto.Enums.Enums;

namespace Prospecto.Controllers
{
    [Authorize]
    public class RolesController : BaseController
    {
        private RoleManager<IdentityRole> roleManager;
        public RolesController(RoleManager<IdentityRole> roleMgr)
        {
            roleManager = roleMgr;
        }

        public ViewResult Index() => View(roleManager.Roles);

        public IActionResult Create() => View("~/Views/Roles/Add.cshtml");

        [HttpPost]
        public async Task<IActionResult> Create([Required] string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    Alert("El Dato Fue Guardado", NotificationType.success);
                    return RedirectToAction("Index");
                }
                else
                {
                    Alert("Necesita un Nombre el Rol", NotificationType.error);
                    return View("~/Views/Roles/Add.cshtml");
                }

            }
            return View("~/Views/Roles/Add.cshtml");
        }

        public IActionResult Update(string id)
        {
            Alert("Opción Desabilitada", NotificationType.info);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(string id)
        {
            Alert("Opción Desabilitada", NotificationType.info);
            return RedirectToAction("Index");
            //IdentityRole role = await roleManager.FindByIdAsync(id);
            //if (role != null)
            //{
            //    IdentityResult result = await roleManager.DeleteAsync(role);
            //    if (result.Succeeded)
            //    {
            //        Alert("El Dato Fue Borrado", NotificationType.success);
            //        return RedirectToAction("Index");
            //    }
            //    else
            //    {
            //        Alert("El Dato No Pudo Ser Borrado", NotificationType.success);
            //        return View("~/Views/Roles/Index.cshtml");
            //    }
            //}
            //else
            //    //ModelState.AddModelError("", "No role found");
            //    Alert("Rol No Se Encontro", NotificationType.success);
            //    return View("Index", roleManager.Roles);
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConFunT</title>

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @*Mensajes de Alerta*@
    <link href="~/lib/sweetalert2/dist/sweetalert2.css" rel="stylesheet" />
    <script src="~/lib/sweetalert2/dist/sweetalert2.min.js"></script>
@*    <link href="~/sweetAlert/sweetalert.css" rel="stylesheet" />
    <script src="~/sweetAlert/sweetalert.min.js"></script>*@
    @*Mensajes de Alerta JavaScript*@
    <script src="~/alertifyjs/alertify.min.js"></script>
    <link href="~/alertifyjs/css/alertify.min.css" rel="stylesheet" />
    <link href="~/alertifyjs/css/themes/default.min.css" rel="stylesheet" />


    @*Loading paginas en procesos*@
    <link href="~/css/LoadingCarga.css" rel="stylesheet" />

    <style>
        .ajs-header {
            background: rgb(249,249,249) !important;
            /*color para el header*/
        }

        .ajs-dialog {
            background: #85E088 !important;
            /*color para el body*/
        }

        .ajs-footer {
            background: rgb(249,249,249) !important;
            /*color para el footer*/
        }


        #loader {
            position: fixed;
            left: 1px;
            top: 1px;
            width: 100%;
            height: 100%;
            z-index: 9999;
            background: url('../images/Loading.gif') 50% 50% no-repeat rgb(249,249,249);
        }
    </style>
    <script type="text/javascript">
        $(document).ready(function () {
            $('body').on('keydown', 'input, select, textarea', function (e) {
                var self = $(this),
                    form = self.parents('form:eq(0)'),
                    submit = (self.attr('type') == 'submit' || self.attr('type') == 'button'),
                    focusable,
                    next;

                if (e.keyCode == 13 && !submit) {
                    focusable = form.find('input,button,a,select,textarea').filter(':visible:not([readonly]):not([disabled]):not([tabindex="-1"])');
                    next = focusable.eq(focusable.index(this) + 1);

                    if (next.length) {
                        next.focus().select();
                    }
                    else {
                        //vuelve al primer tabindex=1
                        var focusable = document.querySelectorAll('input, select, textarea, [tabindex]:not([tabindex="-1"])');
                        var firstFocusable = focusable[0];
                        //form.submit();
                    }
                    return false;
                }
            });
        });
    </script>
</head>
<body>
    <div id="loading">
        <div id="loadingcontent">
            <p id="loadingspinner">
                <img src="~/images/GifCirculos.gif" />
                Un Momento Por Favor...
            </p>
        </div>
    </div>
    <div class="main">
        <div id="loader"></div>
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-white static-top text-black"
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Prospecto</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CProspecto" asp-action="Index">Prospectos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                            </li>
                        </ul>
                        <partial name="_LoginPartial" ></partial>
                    </div>
                </div>
            </nav>
        </header>

        <div class="container">
            <main role="main" class="pb-3">
                @await Html.PartialAsync("_NotificationPanel")
                @RenderBody()
            </main>
        </div>

        <footer class="footer">
            &copy; 2022 - Prospecto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @* Added for JQueryUI (Debug) *@
    <link href="~/lib/jquery-ui/themes/smoothness/jquery-ui.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.js"></script>

    @*<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.js"></script>*@
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/fixedcolumns/3.3.3/js/dataTables.fixedColumns.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jq-2.2.4/dt-1.10.13/fc-3.2.2/fh-3.1.2/r-2.1.0/sc-1.4.2/datatables.min.css" />

    <script src="https://cdn.datatables.net/plug-ins/1.10.25/dataRender/datetime.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>


    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>
<script type="text/javascript">
    @*With the element initially shown, we can hide it slowly:*@
    $("#loader").fadeOut(1000);
</script>

Views/Shared/_NotificationPanel.cshtml
@if (TempData["notification"] != null)
{
    @Html.Raw(TempData["notification"])
}